### ISSUE TITLE
Create a database of already-invited users and don't invite them again

### ISSUE THREAD

**Issue by cole-h** [grahamc/rfc39#3]
https://github.com/NixOS/rfcs/pull/39#issuecomment-601654637

GitHub likes to mess things up, so we should maintain our own database. One downside is that this will likely send another invite to people who have already declined, but this should only be a one-time thing.

**Comment by hugolgst** [comment]
Do you have an idea of what kind of database to use?
I'd be glad to help

**Comment by cole-h** [comment]
Probably anything would suffice, as long as it is persistent. I was planning to try a SQLite database, though.

**Comment by jonringer** [comment]
honestly, I think a flat list (which is easy to edit), with a master gate which adds/removes people would work well

EDIT:
just query, the current member list https://developer.github.com/v3/orgs/members/#list-organization-members, do a diff, and add/remove accordingly

**Comment by hugolgst** [comment]
@jonringer Does this include the members invited but who refused?

**Comment by cole-h** [comment]
No, just like an actual database, we would have to -- unfortunately -- annoy people who have refused in the past once more (and then they'd be on the "already-invited" list and never invited again).

(I would like to say: I'm glad this is sparking discussion. I was one of the last few to get invited through the script, and it'd be nice to invite more people :) )

**Comment by hugolgst** [comment]
I'm glad too, can't wait to be invited!

**Comment by zowoq** [comment]
Could we reuse the [existing maintainer list](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix) for people to opt out of being invited?

Something like:

```nix
  zowoq = {
    email = "..."
    github = "zowoq";
    githubId = ....;
    name = "zowoq";
    invite = false;
  };
```

**Comment by jonringer** [comment]
since it's specific to github, I'm not sure what the value of maintainer handle indirection would be.

Their existence in the list would imply their desire to be added/invited. As long as you make it low effort to remove yourself, I don't think people would mind too much in being added

**Comment by zowoq** [comment]
Do we even need to keep a db/list of already invited users if we give people a way to opt out?

${invites} = ${maintainer_list}-${org_members}-${invite_false}

Just send invites once a week until they remove their entry from the maintainer list or they set `invite = false;` to opt out?

____

> Their existence in the list would imply their desire to be added/invited.

See https://github.com/NixOS/nix/issues/3427

**Comment by hugolgst** [comment]
Do you think that it could be good from a UX point of view?
Thus a user will have to make a PR to add this parameter

**Comment by jonringer** [comment]
> See [NixOS/nix#3427](https://github.com/NixOS/nix/issues/3427)

The list would initially be populated with people already in the team. People would have to manually opt-in, so individuals like him would never receive an email.

For the use case of people leaving... this would be more awkward, we could have a bot list on https://developer.github.com/v3/activity/events/#list-public-organization-events and see if people leave, and have it remove the related individual

**Comment by jonringer** [comment]
We may also be over thinking this as well. Maybe just have a bot listen for something like a `/invite` event on an issue, and it will just automatically invite the person.

This removes all need for state synchronization between github and the local data store.

Edit: similar to https://github.com/marketplace/actions/inclusive-organization

**Comment by hugolgst** [comment]
I agree with you @jonringer but don't you think this will make too much invites to the Nix organization or is it the plan?

**Comment by jonringer** [comment]
Well with the `/invite` convention, you could only invite yourself. So it would be limited to one invite per account. 

I'm sure there would be ways to abuse this. But I think it would be limited.

**Comment by hugolgst** [comment]
So we would make a check when `/invite` called? Or anyone could do it?

**Comment by jonringer** [comment]
This is getting off-topic. I just threw out the bot as an alternative to doing state synchronization.

If others feel like this warrants more discussion, then maybe we would do it in another thread.

**Comment by hugolgst** [comment]
What's the current status of this ?

**Comment by andresilva** [comment]
I opened PR #6 with a simple implementation for this.
